name: note_database
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.8+4
  intl: ^0.18.1
  flutter_staggered_grid_view: ^0.4.0-nullsafety.3
  awesome_dialog: ^3.0.2
  local_auth: ^2.1.6
  flutter_tts: ^3.7.0
  speech_to_text: ^6.1.1
  permission_handler: ^10.2.0
  image_picker: ^0.8.7+5
  provider: ^6.0.5
  shared_preferences: ^2.1.2
  mobile_scanner: ^3.2.0
  qr_flutter: ^4.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0




flutter:
  uses-material-design: true

  assets:
    - assets/images/loginbg.jpg
    - assets/images/loginbgdrop.png

 